const groupIcons  = [
  require("../assets/groupIcons/0.png"),
  require("../assets/groupIcons/1.png"),
  require("../assets/groupIcons/2.png"),
  require("../assets/groupIcons/3.png"),
  require("../assets/groupIcons/4.png"),
  require("../assets/groupIcons/5.png"),
  require("../assets/groupIcons/6.png"),
  require("../assets/groupIcons/7.png"),
  require("../assets/groupIcons/8.png"),
  require("../assets/groupIcons/9.png"),
  require("../assets/groupIcons/10.png"),
  require("../assets/groupIcons/11.png"),
  require("../assets/groupIcons/12.png"),
  require("../assets/groupIcons/13.png"),
  require("../assets/groupIcons/14.png"),
  require("../assets/groupIcons/15.png"),
  require("../assets/groupIcons/16.png"),
  require("../assets/groupIcons/17.png"),
  require("../assets/groupIcons/18.png"),
  require("../assets/groupIcons/19.png"),
  require("../assets/groupIcons/20.png"),
  require("../assets/groupIcons/21.png"),
  require("../assets/groupIcons/22.png"),
  require("../assets/groupIcons/23.png"),
  require("../assets/groupIcons/24.png"),
  require("../assets/groupIcons/25.png"),
  require("../assets/groupIcons/26.png"),
  require("../assets/groupIcons/27.png"),
  require("../assets/groupIcons/28.png"),
  require("../assets/groupIcons/29.png"),
  require("../assets/groupIcons/30.png"),
  require("../assets/groupIcons/31.png"),
  require("../assets/groupIcons/32.png"),
  require("../assets/groupIcons/33.png"),
  require("../assets/groupIcons/34.png"),
  require("../assets/groupIcons/35.png"),
  require("../assets/groupIcons/36.png"),
  require("../assets/groupIcons/37.png"),
  require("../assets/groupIcons/38.png"),
  require("../assets/groupIcons/39.png")
];


export default groupIcons;