const PAGES = {
    LOGGED_OUT: 'Logged Out',
    GROUP_LIST: 'Groups',
    LOGIN: 'Login',
    SIGN_UP: 'Sign Up',
    GROUP: 'Group',
    ADD_TRANSACTION: 'Add Transaction',
    ADD_GROUP: 'Add Group',
    SETTINGS: 'Settings',
    ONBOARDING: 'Onboarding',
    OTP: 'OTP',
    CREATE_GROUP: 'Create Group',
    TRANSACTION_DETAIL: 'Transaction Detail',
    BALANCE: 'Balance',
    SELECT_GROUP: 'Select Group',
    SELECT_PAID_BY: 'Select Paid By',
    GROUP_SPLIT_SCREEN: 'Group Split Screen',
    GROUP_BALANCE: 'Group Balance',
    PAYMENT: 'Payment',
    SEARCH: 'Search',
    EXPENSE: 'Expense',
    ACCOUNT: 'Account',
    SCANNER: 'Scanner',
    UPI_APP_SELECTION: 'UPI App Selection',
    TAB_NAVIGATOR: 'Tab Navigation',
    GROUP_SETTINGS: 'Group Settings',
    FAQ: 'FAQ',
    ABOUT: 'About',
    INVITATION_LANDING_PAGE:"Invitation Landing Page"
};

export default PAGES;
